In [1]:
import pandas as pd
import numpy as np

In [3]:
bios = pd.read_csv('bios.csv')

In [5]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  object
 1   Sex            145500 non-null  object
 2   Full name      145500 non-null  object
 3   Used name      145500 non-null  object
 4   Born           143772 non-null  object
 5   Died           34042 non-null   object
 6   NOC            145499 non-null  object
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  object
 9   Affiliations   95832 non-null   object
 10  Nick/petnames  9145 non-null    object
 11  Title(s)       399 non-null     object
 12  Other names    7167 non-null    object
 13  Nationality    8259 non-null    object
 14  Original name  30739 non-null   object
 15  Name order     7844 non-null    object
dtypes: int64(1), object(15)
memory usage: 17.8+ MB

In [9]:
bios.sample(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
74784,Competed in Olympic Games,Female,Yelena•Gulyayeva (Rodina-),Yelena•Gulyayeva,"14 August 1967 in Moskva (Moscow), Moskva (RUS)",NaN,Russian Federation,75357,182 cm / 64 kg,Moskva Trade Union,NaN,NaN,NaN,NaN,Елена•Гуляева (Родина-),NaN
18083,Competed in Olympic Games,Male,Herbert Clayton•Sumney,Herbert•Sumney,"11 March 1870 in Malta, Illinois (USA)","21 November 1935 in Omaha, Nebraska (USA)",United States,18204,NaN,"Omaha Country Club, Omaha (USA)",NaN,NaN,NaN,NaN,NaN,NaN
45834,Competed in Olympic Games • Other,Male,Johnson Ricardo•González Johnson,Ricardo•González,"17 March 1947 in Cartagena del Chairá, Caquetá...",NaN,Colombia,46181,183 cm / 83 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5078,Competed in Olympic Games,Male,Josef•Moc,Josef•Moc,"22 January 1908 in Mladá Boleslav, Středočeský...","13 July 1999 in Praha (Prague), Hlavní město P...",Czechoslovakia,5097,NaN,"YMCA Praha, Praha (CZE)",NaN,NaN,NaN,Czechia,NaN,NaN
141096,Competed in Olympic Games,Male,Yuta•Nakayama,Yuta•Nakayama,16-Feb-97,NaN,Japan,144635,NaN,"PEC, Zwolle (NED)",NaN,NaN,NaN,NaN,中山•雄太,NaN

### Targets

 - [X] Get rid of the unexpected characters in 'Used name' feature
 - [X] Parse out born and died dates out of the "Born" and "Died" features
 - [X] Parse out born city, regoin, and country out fo the "Born" feature
 - [x] Parse out height and weight from the "Measurements" feature
 - [ ] Get rif of the used irrelevant features

In [10]:
df = bios.copy()

In [24]:
len(df[df['Used name'].str.contains("\^")])

0

In [25]:
df["Clean name"] = df['Used name'].str.replace("•|\^", " ", regex=True)

In [26]:
df.sample(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Clean name
96659,Competed in Olympic Games,Male,Timo Juhani•Seppälä,Timo•Seppälä,"27 June 1968 in Kauhajoki, Etelä-Pohjanmaa (FIN)",NaN,Finland,97437,180 cm / 68 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Timo Seppälä
63552,Competed in Olympic Games,Male,Vilhelm•Vett,Vilhelm•Vett,"31 December 1879 in København (Copenhagen), Ho...","3 December 1962 in Palma de Mallorca, Islas Ba...",Denmark,64029,NaN,"KDY, Hellerup, Gentofte (DEN)",William,NaN,NaN,NaN,NaN,NaN,Vilhelm Vett
113196,Competed in Olympic Games,Female,Gisele•Lima de Oliveira,Gisele•Oliveira,"1 August 1980 in Porto Alegre, Rio Grande do S...",NaN,Brazil,114486,160 cm / 57 kg,BM&F,NaN,NaN,NaN,NaN,NaN,NaN,Gisele Oliveira
26409,Competed in Olympic Games,Male,Luis Claudio•Suárez Sánchez,Claudio•Suárez,"17 December 1968 in Texcoco, México (MEX)",NaN,Mexico,26604,181 cm / 75 kg,"CD Guadalajara, Guadalajara (MEX)",NaN,NaN,NaN,NaN,NaN,NaN,Claudio Suárez
26326,Competed in Olympic Games,Male,Ignacio Francisco•Calderón González,Ignacio•Calderón,"13 December 1943 in Guadalajara, Jalisco (MEX)",NaN,Mexico,26520,178 cm / 74 kg,"CD Guadalajara, Guadalajara (MEX)",Nacho,NaN,NaN,NaN,NaN,NaN,Ignacio Calderón

In [29]:
dummy_data = pd.DataFrame(['180 cm', '180 cm / 68 kg', '78 cm / 74 kg', '50 kg'], columns=["Measurements"])
dummy_data

     Measurements
0          180 cm
1  180 cm / 68 kg
2   78 cm / 74 kg
3           50 kg

In [30]:
dummy_data[ ["Height_cm", "Weight_kg"] ] = dummy_data["Measurements"].str.split('/', expand=True)
dummy_data

     Measurements Height_cm Weight_kg
0          180 cm    180 cm      None
1  180 cm / 68 kg   180 cm      68 kg
2   78 cm / 74 kg    78 cm      74 kg
3           50 kg     50 kg      None

In [31]:
df[["Height_cm", "Weight_kg"]] = df["Measurements"].str.split('/', expand=True)
df.sample(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Clean name,Height_cm,Weight_kg
11907,Competed in Olympic Games,Male,Sergei•Fofanoff,Sergei•Fofanoff,"11 December 1968 in Ribeirão Preto, São Paulo ...",NaN,Brazil,11971,178 cm / 75 kg,Haras Transwall,Guega,NaN,NaN,NaN,NaN,NaN,Sergei Fofanoff,178 cm,75 kg
124378,Competed in Olympic Games,Male,"James ""Jimmy""•Feigen",Jimmy•Feigen,"26 September 1989 in Hilo, Hawaiʻi (USA)",NaN,United States,126677,196 cm / 98 kg,"Texas Longhorns, Austin (USA)",NaN,NaN,NaN,NaN,NaN,NaN,Jimmy Feigen,196 cm,98 kg
55,Competed in Olympic Games,Female,Valda•Lake,Valda•Lake,"11 October 1968 in Torquay, England (GBR)",NaN,Great Britain,56,173 cm / 61 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valda Lake,173 cm,61 kg
43536,Competed in Olympic Games,Male,Petre•Cișmigiu,Petre•Cișmigiu,"12 June 1915 in Bolhrad, Odesa (UKR)",2006,Romania,43872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Petre Cișmigiu,NaN,NaN
143250,Competed in Olympic Games,Female,Nihel•Landolsi (-Bouchoucha),Nihel•Landolsi,01-Jul-95,NaN,Tunisia,146892,NaN,NaN,NaN,NaN,NaN,NaN,نهال•الأندلسي (-بوشوشة),NaN,Nihel Landolsi,NaN,NaN

In [32]:
df["Height_cm"] = df["Height_cm"].str.extract(r'(\d+)')
df["Weight_kg"] = df["Weight_kg"].str.extract(r'(\d+)')
df.sample(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Clean name,Height_cm,Weight_kg
109995,Competed in Olympic Games,Female,Trine Bjerke•Rønning,Trine•Rønning,"14 June 1982 in Trondheim, Trøndelag (NOR)",NaN,Norway,111203,164 cm / 61 kg,"Kolbotn IL, Kolbotn, Oppegård (NOR)",NaN,NaN,NaN,NaN,NaN,NaN,Trine Rønning,164,61
97839,Competed in Olympic Games,Male,Birger Olaus•Vestermo,Birger•Vestermo,"27 February 1930 in Salangen, Troms og Finnmar...",NaN,Norway,98630,NaN,"Øvre Salangen IL, Sjøvegan (NOR)",NaN,NaN,NaN,NaN,NaN,NaN,Birger Vestermo,NaN,NaN
136537,Competed in Youth Olympic Games,Male,Luka•Mtchedliani,Luka•Mtchedliani,30-Apr-03,NaN,Georgia,139763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Luka Mtchedliani,NaN,NaN
142143,Competed in Olympic Games,Female,Olivia Juliet Bridget•Chance,Olivia•Chance,"5 October 1993 in Auckland, Auckland (NZL)",NaN,New Zealand,145740,162 cm,Brisbane Roar (AUS),NaN,NaN,NaN,NaN,NaN,NaN,Olivia Chance,162,NaN
7730,Competed in Olympic Games,Male,Grzegorz•Skrzecz,Grzegorz•Skrzecz,"25 August 1957 in Warszawa (Warsaw), Mazowieck...",15-Feb-23,Poland,7771,186 cm / 90 kg,"Gwardia Warszawa, Warszawa (POL)",NaN,NaN,NaN,NaN,NaN,NaN,Grzegorz Skrzecz,186,90

In [37]:
Date_pattern = r'(\d+[\s|-]\w+[\s|-]\d+)'
df["Born_date"] = df["Born"].str.extract(Date_pattern)

In [43]:
df.sample(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Title(s),Other names,Nationality,Original name,Name order,Clean name,Height_cm,Weight_kg,Born_date,Died_date
21349,Competed in Olympic Games,Male,Pablo•Uribe Henao,Pablo•Uribe,"21 February 1931 in Bogotá, Bogotá (COL)",13-May-21,Colombia,21500,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Pablo Uribe,NaN,NaN,21 February 1931,13-May-21
65501,Competed in Olympic Games,Male,Cyril Hillyard•Coaffee,Cyril•Coaffee,"14 February 1897 in Edmonton, England (GBR)","2 July 1945 in Winnipeg, Manitoba (CAN)",Canada,65997,176 cm / 70 kg,"North End Amateur Athletic Club, Winnipeg (CAN)",...,NaN,NaN,NaN,NaN,NaN,Cyril Coaffee,176,70,14 February 1897,2 July 1945
105484,Competed in Olympic Games,Female,Grace E.•Upshaw,Grace•Upshaw,"25 September 1975 in Berkeley, California (USA)",NaN,United States,106535,173 cm / 59 kg,"Nike, Beaverton (USA)",...,NaN,NaN,NaN,NaN,NaN,Grace Upshaw,173,59,25 September 1975,NaN
72857,Competed in Olympic Games,Male,Odiya•Silweya,Odiya•Silweya,01-Jan-59,NaN,Malawi,73411,172 cm / 70 kg,NaN,...,NaN,NaN,NaN,NaN,NaN,Odiya Silweya,172,70,01-Jan-59,NaN
16526,Competed in Olympic Games,Male,Miklós•Somogyi,Miklós•Somogyi,"19 August 1962 in Budapest, Budapest (HUN)",NaN,Hungary,16642,194 cm / 90 kg,"Ferencvárosi TC, Budapest (HUN)",...,NaN,NaN,NaN,NaN,NaN,Miklós Somogyi,194,90,19 August 1962,NaN

In [39]:
df["Died_date"] = df["Died"].str.extract(Date_pattern)

In [41]:
df.sample(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Title(s),Other names,Nationality,Original name,Name order,Clean name,Height_cm,Weight_kg,Born_date,Died_date
34111,Competed in Olympic Games,Male,Vladimir•Shmakov,Vladimir•Shmakov,08-Feb-73,NaN,Uzbekistan,34375,NaN,NaN,...,NaN,NaN,NaN,Владимир•Шмаков,NaN,Vladimir Shmakov,NaN,NaN,08-Feb-73,NaN
132409,Competed in Olympic Games,Male,Govert•Viergever,Govert•Viergever,"29 July 1989 in Amsterdam, Noord-Holland (NED)",NaN,Netherlands,135275,184 cm / 85 kg,"Nereus, Amsterdam (NED)",...,NaN,NaN,NaN,NaN,NaN,Govert Viergever,184,85,29 July 1989,NaN
77384,Competed in Olympic Games,Female,"Anne Rochelle ""Shelly""•Steely (-Ramirez)",Shelly•Steely,"23 October 1962 in Reading, Pennsylvania (USA)",NaN,United States,77975,170 cm / 55 kg,"Mizuno Track Club, Osaka (JPN)",...,NaN,NaN,NaN,NaN,NaN,Shelly Steely,170,55,23 October 1962,NaN
39721,Competed in Olympic Games,Male,František•Maloň,František•Maloň,12-Mar-13,NaN,Czechoslovakia,40028,NaN,"ČVK Brno, Brno (CZE)",...,NaN,NaN,Czechia,NaN,NaN,František Maloň,NaN,NaN,12-Mar-13,NaN
99768,Competed in Olympic Games,Male,František•Kučera,František•Kučera,"3 February 1968 in Praha (Prague), Hlavní měst...",NaN,Czechia,100567,188 cm / 93 kg,"Sparta Praha, Praha (CZE) / Philadelphia Flyer...",...,NaN,NaN,NaN,NaN,NaN,František Kučera,188,93,3 February 1968,NaN

In [45]:
Location_Pattern = r'in\s([\w\s()-]+),\s([\w\s()-]+)\s\((\w+)\)'
df[ ["Born_city", "Born_region", "Born_country"] ]  = df["Born"].str.extract(Location_Pattern, expand=True)
df.sample(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Clean name,Height_cm,Weight_kg,Born_date,Died_date,Born_city,Born_region,Born_country
98044,Competed in Olympic Games,Male,Michael•Waissnix,Michael•Waissnix,"22 May 1904 in Reichenau an der Rax, Niederöst...","13 October 1980 in Reichenau an der Rax, Niede...",Austria,98836,NaN,"?, Payerbach (AUT)",...,NaN,NaN,Michael Waissnix,NaN,NaN,22 May 1904,13 October 1980,Reichenau an der Rax,Niederösterreich,AUT
103217,Competed in Olympic Games,Female,Anet-Jacqueline•Buschmann,Anet-Jacqueline•Buschmann,"18 December 1982 in Varna, Varna (BUL)",NaN,Bulgaria,104189,180 cm / 75 kg,"Cherno More, Varna (BUL)",...,Анет-Жаклин•Бушман,NaN,Anet-Jacqueline Buschmann,180,75,18 December 1982,NaN,Varna,Varna,BUL
115730,Competed in Olympic Games,Male,Reineris•Salas Pérez,Reineris•Salas,"17 March 1987 in La Habana (Havana), Ciudad de...",NaN,Cuba,117097,180 cm / 86 kg,"Cerro Pelado, La Habana (CUB)",...,NaN,NaN,Reineris Salas,180,86,17 March 1987,NaN,La Habana (Havana),Ciudad de La Habana,CUB
141237,Competed in Olympic Games,Male,Dmitry Nikolayevich•Gruzdev,Dmitry•Gruzdev,"13 March 1986 in Astana, Astana (KAZ)",NaN,Kazakhstan,144776,NaN,Astana - Premier Tech (KAZ),...,Дмитрий Николаевич•Груздев,NaN,Dmitry Gruzdev,NaN,NaN,13 March 1986,NaN,Astana,Astana,KAZ
57465,Competed in Olympic Games,Male,"Oskar David ""Oskari""•Friman",Oskari•Friman,"27 January 1893 in Usadishche, Leningrad (RUS)","19 October 1933 in Vyborg, Leningrad (RUS)",Finland,57872,NaN,"Viipurin Voimailijat, Vyborg (RUS)",...,NaN,NaN,Oskari Friman,NaN,NaN,27 January 1893,19 October 1933,Usadishche,Leningrad,RUS

In [47]:
columns_to_keep = ["Clean name", "Sex", "Height_cm", "Weight_kg", "Born_date", "Died_date", "Born_city", "Born_region", "Born_country"]
df_clean=df[columns_to_keep]
df_clean.sample(5)

,Clean name,Sex,Height_cm,Weight_kg,Born_date,Died_date,Born_city,Born_region,Born_country
95985,Yauhen Redzkin,Male,184,81,2 February 1970,NaN,Khanty-Mansiysk,Khanty-Mansi Avtonomny Okrug,RUS
88220,Nataliya Tsyganova,Female,162,50,7 February 1971,NaN,Bishkek,Bishkek,KGZ
67106,Kalle Järvinen,Male,188,90,27 March 1903,25 August 1941,Jyväskylä,Keski-Suomi,FIN
124969,Steph Magiros,Female,150,50,5 May 1991,NaN,Paddington,New South Wales,AUS
31425,Jaime Puig,Male,200,105,17 June 1957,NaN,Moncada y Reixach,Barcelona,ESP